name: Continuous Integration

on:
  [push, pull_request]:
    branches:
    - master

jobs:
  go-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16.3'
        
    - name: Setup GraphViz
      uses: ts-graphviz/setup-graphviz@v1
    
    - name: Install dependencies
      run: |
        go version
        go get -u golang.org/x/lint/golint
      
    - name: Run build
      run: go build
      
    - name: Run vet & lint
      run: |
        go vet
        golint
    
    - name: Run testing
      run: cd test && go test dfatoolkit_test.go -v