name: DFA-Tooklit Build Test

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Go
      uses: actions/setup-go@v2
    
    - name: Install dependencies
      run: go version
      
    - name: Run vet
      run: cd GO && go vet .
    
    - name: Run testing
      run: cd GO/DFA_Toolkit/test && go test -v