name: DFA-Tooklit Build Test

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16.3'
        
    - name: Setup GraphViz
      uses: ts-graphviz/setup-graphviz@v1
    
    - name: Install dependencies
      run: |
        go version
        go get -u golang.org/x/lint/golint
      
    - name: Run build
      run: cd GO/DFA_Toolkit && go build . 
      
    - name: Run vet & lint
      run: |
        cd GO/DFA_Toolkit
        go vet .
        golint .
    
    - name: Run testing
      run: cd GO/DFA_Toolkit/test && go test -v