[package]
name = "dfa_toolkit"
version = "0.1.0"
authors = ["Cherrett <cherrettdaniel@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
